# Generated by Django 4.2.7 on 2023-11-28 20:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import email_module.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'label',
                'verbose_name_plural': 'labels',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='email title')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='attached_files', validators=[email_module.validators.validate_file_size])),
                ('draft', models.BooleanField(default=False)),
                ('archived_by_user', models.ManyToManyField(blank=True, related_name='is_archived_by_user', to=settings.AUTH_USER_MODEL)),
                ('bcc_receivers', models.ManyToManyField(blank=True, related_name='bcc_receivers', to=settings.AUTH_USER_MODEL)),
                ('cc_receivers', models.ManyToManyField(blank=True, related_name='cc_receivers', to=settings.AUTH_USER_MODEL)),
                ('deleted_by_user', models.ManyToManyField(blank=True, related_name='is_deleted_by_user', to=settings.AUTH_USER_MODEL)),
                ('direct_receivers', models.ManyToManyField(blank=True, related_name='direct_receivers', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(blank=True, related_name='email_labels', to='email_module.label', verbose_name='email_labels')),
                ('read_by_user', models.ManyToManyField(blank=True, related_name='is_read_by_user', to=settings.AUTH_USER_MODEL)),
                ('replied_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_module.email')),
                ('sender', models.ForeignKey(on_delete=models.SET('deleted_account'), related_name='sent_Emails', to=settings.AUTH_USER_MODEL)),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_module.signature')),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'emails',
            },
        ),
    ]
